### ISSUE TITLE
Static use explain

### ISSUE THREAD

**Issue by IlanVokov** [ctodobom/OpenCV-3.1.0-Android#1]
hi can you explain please how to use your library without OpenCV manager api?
i have read about static use but can't find the archs

**Comment by allgood** [comment]
Hi,

first of all, this is not my library, I just moved the original OpenCV Android library to this project in order to be able to use it from Gradle.

My app uses OpenCV Manager, so, I think I don't know how to do what you are asking.

Wish you good luck.

**Comment by ballenjr** [comment]
Hello,

I believe I do know how to add the static libraries. I have done it within a cordova plugin as well as a separate Android Studio project. However when I fork this repo and add the libraries like so: https://github.com/ballenjr/OpenCV-3.1.0-Android/commit/ab1713f0431f4efbd4e2d0a434eb805913bf858b

Then attempt to use jitpack.io api

```
com.github.ballenjr:OpenCV-3.1.0-Android:-SNAPSHOT
```

Gradle/Maven fails to find the repo.  Everything else is the same as how I had it working based on your instructions, except my name replaces yours. 

Would you have any idea why this would be? Or would you be willing to mimic my commit in a separate release so that I could test it using your "repo" mapping?

I know it works when I add the static libraries through cordova and link to your repo for the java bindings, I would really like to see if it will work with everything together in the same repo.

**Comment by ballenjr** [comment]
Essentially all that I did was open this project in Android Studio view it in the Android context using the dropdown here:
![image](https://cloud.githubusercontent.com/assets/3208067/17269704/87b97764-5604-11e6-8593-015639df8bd1.png)

Then File > New > Folder > JNI

Then add the different architectures like so: 
![image](https://cloud.githubusercontent.com/assets/3208067/17269722/2d51cb22-5605-11e6-86ed-5b4fee338ce5.png)

You can even paste the folders directly into Android Studio.

**Comment by ballenjr** [comment]
Nevermind, I logged into jitpack and found the build log. Turns out I didn't force the NDK back on. All I really needed was the gradle.properties file from this commit: https://github.com/ballenjr/OpenCV-3.1.0-Android/commit/ec838881ec80348c77890b970b0cd2b6ad58728a

It turns out also, that compiling this way renames the static libraries to match the project for some weird reason. So had to update the default convention in the helper class: https://github.com/ballenjr/OpenCV-3.1.0-Android/commit/8bd2847850e28fe2c4ff59ba80a3bcc5ca2b9662

Unfortunately, though, it seems that jitpack has packed the static files wrong somehow. They are all giving UnsatisfiedLinkException when I try to System.loadLibrary("OpenCV"). Digging into the APK I see that the files that were put in are all around 5KB. Which makes me suspect jitpack. If anyone has any insight here it would be greatly appreciated. Otherwise I will be investigating further.

**Comment by ballenjr** [comment]
UPDATE: I was able to get one architecture working.

Maybe some sort of size limit? The last step I tried before joy was reducing how many arch's I copied over, just one. Other steps that I couldn't verify/rule out, were updating everything sdk and ide related. Didn't touch cordova but cordova did use the latest build tools for the final product(24.0.1). Also I didn't modify the gradle settings for min/target/compile(sdk) this time either. But that, I would think, only effects remote(jitpack) not local. 

Maybe I will try adding another chip type if the need arises. For now its working as long as you run it on the armv7 that I was able to include. Enjoy!

**Comment by allgood** [comment]
Hi ballenjr,

sorry for the delay on reading your messages.

Are you building the binary libraries from source through gradle also? One
problem I have is that I couldn't build it and used the released ones from
the OpenCV project.

Best regards,
claudemir

Em sáb, 30 de jul de 2016 às 14:32, ballenjr notifications@github.com
escreveu:

**Comment by ballenjr** [comment]
Hello, ~~I did both actually~~. My bad, I misunderstood at first. Both branches include the compiled binaries. I don't know how to create that as a gradle task.

First I didn't want to compile either. So I
used the precompiled binaries in my master. But then I had a problem using
grabCut. So I went to the source to see if I could find a reason. Then I
found out that 3.1.0 wasn't even the latest commit. So I compiled from
master and put the result into my Latest-Master branch. Which I am about to
update. I found a segfault that I have no idea how to track down or even
repeat reliably. So I pulled down the bleeding edge and will give it a
shot. If it still happens I will try the latest stable release from May.
Which I will put in another branch. I am also preparing to let the
contributors know about he segfault and try to give the best idea I can on
how to produce it.

Both branches are working from jitpack too. So you are welcome to grab them
and try them out. Or follow my example and pick another release that you
like better.

I don't really understand why the 2.4.\* has the later commits than 3.1.0. I
am not even sure what the difference is between the branches other than
perhaps project structure. Other than that it doesn't really make sense to
me to continue committing to a branch that was superseded.

**Comment by ballenjr** [comment]
Another thing was that the compiled native binaries that I used at first
were out of sync with this repos Java bindings. It was missing a method
signature that the examples used. So I ended up replacing the Java to match
the native that I was using. Funny enough missing the one signature didn't
raise any flags until I tried to call it.

**Comment by ballenjr** [comment]
~~I did both actually~~. My bad, I misunderstood at first. Both branches include the compiled binaries. I don't know how to create that as a gradle task.

But if you know of any reading material that explains how to do this I would love to take a look.

**Comment by allgood** [comment]
I tried with no success. I think it is very difficult to build it from source since it needs kernel header files.

Will try again someday.

Regards

Em 5 de agosto de 2016 01:13:46 BRT, ballenjr notifications@github.com escreveu:

> ~~I did both actually~~. My bad, I misunderstood at first. Both
> branches include the compiled binaries. I don't know how to create that
> as a gradle task.
> 
> But if you know of any reading material that explains how to do this I
> would love to take a look.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ctodobom/OpenCV-3.1.0-Android/issues/1#issuecomment-237751084

## 

E-mail enviado do meu celular Android usando K-9 Mail. Por favor, desculpe minha brevidade.

**Comment by ballenjr** [comment]
Would you at least be able to tell me how you put that project together? I am new to gradle and Android Studio. I cannot see where the appropriate options are that cause this project to be compiled to AAR. Or what the significance of the project structure is either. I would like to be able to set something like this up from scratch.

**Comment by allgood** [comment]
To be honest, I don't remember exactly!

I am new to all of Android development also and Open Note Scanner is the only app I've made. This repo was made mainly to separate third party code from mine.

I think I just moved the code that opencv guides instructs to put inside the app structure to a separated one.

About the building, I am pretty sure all is defined on build.gradle and associated files.

Best regards

Em 5 de agosto de 2016 22:52:15 BRT, ballenjr notifications@github.com escreveu:

> Would you at least be able to tell me how you put that project
> together? I am new to gradle and Android Studio. I cannot see where the
> appropriate options are that cause this project to be compiled to AAR.
> Or what the significance of the project structure is either. I would
> like to be able to set something like this up from scratch.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ctodobom/OpenCV-3.1.0-Android/issues/1#issuecomment-237999692

## 

E-mail enviado do meu celular Android usando K-9 Mail. Por favor, desculpe minha brevidade.

**Comment by devbrevity** [comment]
Hello guys, is there any update ? are you get success on  implementing static libraries ?

**Comment by htnghiaxx** [comment]
Hi ctodobom,
Are there any way to VideoCapture from a streaming video url ?

Thanks.

**Comment by allgood** [comment]
Can't tell you about this. Maybe you shoud ask to the upstream project.

Best regards,
Claudemir

Em qui, 29 de set de 2016 às 13:24, htnghiaxx notifications@github.com
escreveu:

**Comment by allgood** [comment]
OpenCV Manager was removed from Google Play, Open Note Scanner is not compatible with newer versions of OpenCV.

This repository was made almost exclusively to be used with OpenNoteScanner, but there is no problem if anybody uses it with another projects. It will stay here.

Static binaries was implemented for the version of OpenNoteScanner available on Google Play, there is a branch on its repository that builds it. The commit that implemented static binaries is at https://github.com/ctodobom/OpenNoteScanner/commit/5e6c52e2f4685ad18dcec35eb5506c8cbae1ba7d

Best regards,
Claudemir
