### ISSUE TITLE
Issues in resolving symbols

### ISSUE THREAD

**Issue by RaviDinesh1999** [ctodobom/OpenCV-3.1.0-Android#5]
Hi, 
The error 'cannot resolve symbol variable styleable' occuring in both CameraBrigeViewBase.Java and CameraGLSurfaceView.Java

**Comment by bohniges** [comment]
@RaviDinesh1999 Hi,
OffTopic: Because the issue isn't yet closed, I give it a try to solve it... (is my very 1st "contribution")
Topic: Since I got the same exception when **import**ing an OpenCV-Library-Version as **module** (and setting dependency an so on...) I solved the issue as follows:
In **Module** (Library) `build.gradle` File; `android` - `sourceSets` - item `res.srcDirs = ['/build/master_pack-android/opencv/modules/java/android_sdk/android_gradle_lib/res']`
reduce that to `res.srcDirs = ['res']`

**Comment by allgood** [comment]
@bohniges , is this changes to build.gradle of this project?

**Comment by bohniges** [comment]
Hi C.
At this point I have to explain in more detail:
I used your OpenCV-DocumentScanner. There you implemented this project / library. An alternative to this `implementation` is module import (as roughly described above).
My answer / issue solution relates actually to any project using the implementation-alternative.
So nothing is to change in your OpenCV project / library.

**Comment by allgood** [comment]
thank you
